# Site settings for TechStuffIGuess
title: TechStuffIGuess
description: >-
  A place where I write about Intune, Microsoft 365, and other IT stuff I guess.
baseurl: "/TechStuffIGuess" # the subpath of your site, e.g. /blog
url: "https://sargeschultz11.github.io" # the base hostname & protocol
github_username: sargeschultz11

# Build settings
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0 # You can change this to another GitHub Pages supported theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  series:
    output: true
    permalink: /:collection/:name/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Ryan Schultz"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"

# Navigation
header_pages:
  - about.md
  - categories/intune.md
  - categories/microsoft365.md
  - categories/general-it.md
  - series.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .idea/
  - .vscode/
  - README.md